INSERT INTO clients (name, lastname) VALUES ('Dayana', 'Granja');
INSERT INTO clients (name, lastname) VALUES ('Andres', 'Guzman');
INSERT INTO clients (name, lastname) VALUES ('Paulo', 'Devries');
INSERT INTO clients (name, lastname) VALUES ('Ximena', 'Rodriguez');
INSERT INTO clients (name, lastname) VALUES ('Daniel', 'Belalcasar');
INSERT INTO clients (name, lastname) VALUES ('Leonardo', 'Martinez');
INSERT INTO clients (name, lastname) VALUES ('Santiago', 'Guerrero');
INSERT INTO clients (name, lastname) VALUES ('Jose', 'Munares');
INSERT INTO clients (name, lastname) VALUES ('Samuel', 'Gutierrez');